
import { University, QuizQuestion, BingoCell, SurvivalTip, Sticker, FoodItem } from './types';

export const UNIVERSITIES: University[] = [
  { id: 'just', nameEn: 'Jordan University of Science and Technology (JUST)', nameAr: 'جامعة العلوم والتكنولوجيا الأردنية' },
  { id: 'uj', nameEn: 'University of Jordan (UJ)', nameAr: 'الجامعة الأردنية' },
  { id: 'yu', nameEn: 'Yarmouk University', nameAr: 'جامعة اليرموك' },
  { id: 'hu', nameEn: 'Hashemite University', nameAr: 'الجامعة الهاشمية' },
  { id: 'bau', nameEn: 'Al-Balqa Applied University', nameAr: 'جامعة البلقاء التطبيقية' },
  { id: 'mutah', nameEn: 'Mutah University', nameAr: 'جامعة مؤتة' },
  { id: 'aau', nameEn: 'Al-Ahliyya Amman University', nameAr: 'جامعة عمان الأهلية' },
];

export const INITIAL_BINGO: BingoCell[] = [
  { id: 1, textEn: "Late to 8 AM lecture", textAr: "تأخرت على محاضرة الـ ٨", checked: false },
  { id: 2, textEn: "Forgot University ID", textAr: "نسيت الهوية الجامعية", checked: false },
  { id: 3, textEn: "Ate Mansaf & Slept", textAr: "ضربت منسف ونمت", checked: false },
  { id: 4, textEn: "Professor cancelled class", textAr: "الدكتور لغى المحاضرة", checked: false },
  { id: 5, textEn: "Begged for grades", textAr: "تشحد علامات", checked: false },
  { id: 6, textEn: "Lost in Engineering Bldg", textAr: "ضعت بمبنى الهندسة", checked: false },
  { id: 7, textEn: "Drank 3+ Coffees", textAr: "شربت ٣ قهاوي وفوق", checked: false },
  { id: 8, textEn: "Used 'Ya Zame' 50 times", textAr: "حكيت 'يا زلمة' ٥٠ مرة", checked: false },
  { id: 9, textEn: "Broke (End of month)", textAr: "مفلس (اخر الشهر)", checked: false },
  { id: 10, textEn: "Bus broke down", textAr: "الباص تعطل", checked: false },
  { id: 11, textEn: "Pretended to take notes", textAr: "عامل حالك بتكتب نوتس", checked: false },
  { id: 12, textEn: "FREE SPACE (Coffee)", textAr: "مساحة مجانية (قهوة)", checked: true }, // Center
  { id: 13, textEn: "Argued about parking", textAr: "تهاوشت على مصف", checked: false },
  { id: 14, textEn: "Skipped Thursday", textAr: "غبت يوم الخميس", checked: false },
  { id: 15, textEn: "Cat on campus", textAr: "شفت بسة بالجامعة", checked: false },
  { id: 16, textEn: "Ordered food during lecture", textAr: "طلبت أكل بالمحاضرة", checked: false },
  { id: 17, textEn: "Forgot assignment deadline", textAr: "نسيت تسليم الواجب", checked: false },
  { id: 18, textEn: "Group project drama", textAr: "دراما مشروع التخرج", checked: false },
  { id: 19, textEn: "Library for sleeping", textAr: "المكتبة للنوم فقط", checked: false },
  { id: 20, textEn: "Failed first quiz", textAr: "رسبت بأول كويز", checked: false },
  { id: 21, textEn: "Borrowed a pen", textAr: "سرقت قلم (استعرت)", checked: false },
  { id: 22, textEn: "Stuck in Amman Traffic", textAr: "علقت بأزمة عمان", checked: false },
  { id: 23, textEn: "Phone battery 1%", textAr: "شحن تلفونك ١٪", checked: false },
  { id: 24, textEn: "Saw high school friend", textAr: "شفت صاحبك من المدرسة", checked: false },
  { id: 25, textEn: "Actually studied", textAr: "درست عنجد", checked: false },
];

export const INITIAL_TIPS: SurvivalTip[] = [
  {
    category: 'food',
    titleEn: "The Shawerma Rule",
    titleAr: "قانون الشاورما",
    contentEn: "Never buy the cheapest Shawerma near campus gates. Your stomach has exams too.",
    contentAr: "إوعك تشتري أرخص شاورما عند بوابة الجامعة. معدتك كمان عندها امتحانات."
  },
  {
    category: 'exam',
    titleEn: "The 'Inshallah' Strategy",
    titleAr: "استراتيجية 'إن شاء الله'",
    contentEn: "When you don't know the answer, write clearly and confidently. Confusion is key.",
    contentAr: "لما ما تعرف الجواب، اكتب بخط واضح وبثقة. الخربطة هي مفتاح النجاح."
  },
];

export const STICKERS: Sticker[] = [
  { id: 1, url: "📚", labelEn: "Exam Mode", labelAr: "وضع الامتحانات" },
  { id: 2, url: "☕", labelEn: "Fuel", labelAr: "وقود" },
  { id: 3, url: "😴", labelEn: "8 AM Class", labelAr: "محاضرة الثمانية" },
  { id: 4, url: "😱", labelEn: "Deadline", labelAr: "تسليم" },
  { id: 5, url: "💸", labelEn: "Broke", labelAr: "طفران" },
  { id: 6, url: "🚌", labelEn: "Bus Life", labelAr: "حياة الباصات" },
];

export const FOOD_ITEMS: FoodItem[] = [
    { id: 'shawerma', nameEn: 'Shawerma', nameAr: 'شاورما', icon: '🌯', color: '#FCD34D' },
    { id: 'mansaf', nameEn: 'Mansaf Cup', nameAr: 'كاسة منسف', icon: '🍚', color: '#FCA5A5' },
    { id: 'zinger', nameEn: 'Zinger Sandwich', nameAr: 'ساندويش زنجر', icon: '🍔', color: '#FDBA74' },
    { id: 'falafel', nameEn: 'Falafel', nameAr: 'فلافل', icon: '🧆', color: '#86EFAC' },
    { id: 'indomie', nameEn: 'Indomie', nameAr: 'إندومي', icon: '🍜', color: '#FDE047' },
    { id: 'coffee', nameEn: 'Iced Coffee', nameAr: 'آيس كوفي', icon: '🥤', color: '#D4D4D8' },
];

export const TRANSLATIONS = {
  en: {
    title: "Fun Student Pack",
    subtitle: "The survival kit for Jordanian Students",
    startQuiz: "Personality Test",
    university: "University",
    selectUni: "Select your University",
    loading: "Brewing Arabic Coffee...",
    results: "Your Result",
    share: "Share Result",
    playBingo: "Bingo",
    memeGallery: "Memes",
    survivalGuide: "Survival Guide",
    stickers: "Stickers",
    planner: "Study Planner",
    back: "Back",
    next: "Next",
    generateNew: "Ask AI for New Content",
    score: "Score",
    download: "Download Pack",
    aiStudio: "AI Studio",
    sketchGen: "Sketch Generator",
    enterPrompt: "Enter a funny situation (e.g., Cat studying engineering)",
    generate: "Generate",
    generating: "Generating... This might take a moment",
    addCaption: "Add Text",
    captionPlaceholder: "Type here...",
    addTextLayer: "Add Text Layer",
    textControls: "Text Controls",
    deleteLayer: "Delete",
    dragToMove: "Drag text to move it around",
    textColor: "Color",
    textBg: "Style",
    gpaCalc: "Al-Ma3ddal (GPA)",
    currentGpa: "Current GPA",
    creditHours: "Passed Hours",
    calculate: "Calculate Fate",
    studentStatus: "Your Status",
    emailWizard: "Email Wizard",
    emailTopic: "Topic (e.g., Missing Exam)",
    emailRecipient: "Recipient Name",
    emailTone: "Desperation Level",
    toneFormal: "Professional",
    toneDesperate: "Begging (Desperate)",
    generateEmail: "Draft Email",
    copyText: "Copy Text",
    foodRoulette: "Food Roulette",
    spin: "Spin Wheel",
    eatThis: "You should eat:",
    dashboard: "Dashboard",
    memeTopicLabel: "Meme Topic",
    memeTopicPlaceholder: "e.g., Mansaf, Traffic, Exams...",
  },
  ar: {
    title: "حزمة الطلاب الطائشة",
    subtitle: "عدة النجاة لطلاب الجامعات الأردنية",
    startQuiz: "اختبار الشخصية",
    university: "الجامعة",
    selectUni: "اختر جامعتك",
    loading: "بنغلي القهوة...",
    results: "نتيجتك",
    share: "شارك النتيجة",
    playBingo: "بينجو الجامعات",
    memeGallery: "معرض الميمز",
    survivalGuide: "دليل النجاة",
    stickers: "ملصقات",
    planner: "جدول دراسي",
    back: "رجوع",
    next: "التالي",
    generateNew: "اطلب محتوى جديد",
    score: "النتيجة",
    download: "حمل الحزمة",
    aiStudio: "الرسام الذكي",
    sketchGen: "حول أفكارك لرسمة",
    enterPrompt: "اوصف الرسمة اللي ببالك (مثلاً: طالب بدرس بالباص، دكتور بضحك...)",
    generate: "ارسم",
    generating: "الرسام بشتغل... اصبر شوي",
    addCaption: "أضف نص",
    captionPlaceholder: "اكتب النص هون...",
    addTextLayer: "أضف نص جديد",
    textControls: "تحكم بالنص",
    deleteLayer: "حذف",
    dragToMove: "اسحب النص عشان تحركه",
    textColor: "اللون",
    textBg: "الستايل",
    gpaCalc: "حاسبة المعدل",
    currentGpa: "المعدل الحالي",
    creditHours: "الساعات المقطوعة",
    calculate: "احسب مصيرك",
    studentStatus: "وضعك الدراسي",
    emailWizard: "كاتب الإيميلات",
    emailTopic: "الموضوع (مثلاً: غياب امتحان)",
    emailRecipient: "اسم الدكتور/ة",
    emailTone: "مستوى اليأس",
    toneFormal: "رسمي ومحترم",
    toneDesperate: "شحدة وبكائيات",
    generateEmail: "اكتب الإيميل",
    copyText: "نسخ النص",
    foodRoulette: "عجلة الجوع",
    spin: "لف العجلة",
    eatThis: "لازم توكل:",
    dashboard: "الرئيسية",
    memeTopicLabel: "موضوع الميم",
    memeTopicPlaceholder: "مثلاً: منسف، أزمة السير، فاينل...",
  }
};
